#Deployed *-models-gen projects on server
deployed.projects=etd-jars-data-code,etd-jars-models,etd-jars-models-gen

#T24 user name for authorizing record
t24username.authorizer=SHOJIB2

#context for web-service
context=

#T24 User name used for introspection and deployment (TAFJ)
username=SHOJIB1

#T24 branch (used in XML header envelope) for deployment
branch=

#T24 Encrypted password used for introspection and deployment (TAFJ)
password={encoded}pjzKruVt1sU=

#T24 encrypted password for authorizing record
t24password.authorizer={encoded}pjzKruVt1sU=

#Protocol: ftp, sftp or local (TAFC & TAFJ: used for *.b and *.d file transfer)
protocol=ws

#T24 host name to connect to (IP address or Domain name)
host=172.16.1.74

#T24 Web service (TAFJ) port number to connect
ws.port=9081

