<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.temenos.maven</groupId>
        <artifactId>t24-core</artifactId>
        <version>22.3</version>
    </parent>

    <groupId>com.temenos.packager.tafj.demo</groupId>
    <artifactId>etd-jars-packager</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>t24-package</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>com.odcgroup.maven.plugin</groupId>
                <artifactId>t24-project-maven-plugin</artifactId>
                <configuration>
                    <type>TAFJ</type>
                    <release>R19</release>
                    <componentName>EB_Sample</componentName>
                    <rev>1</rev>
                    <version>19.0</version>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>com.temenos.packager.tafj.demo</groupId>
            <artifactId>etd-jars-data-code</artifactId>
            <version>${project.version}</version>
            <type>tafj-project</type>
        </dependency>
        <dependency>
            <groupId>com.temenos.packager.tafj.demo</groupId>
            <artifactId>etd-jars-models-gen</artifactId>
            <version>${project.version}</version>
            <type>ds-generated</type>
            <classifier>xmlt24i</classifier>
        </dependency>
    </dependencies>
</project>
